# Required metadata
sonar.projectKey=stepify
sonar.organization=abdulraheem1308
# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Stepify
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=stepify_app/lib,stepify_backend/src

# Exclusions
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**,**/*.spec.ts,**/dist/**,**/node_modules/**,**/*.js

# Coverage reports
sonar.javascript.lcov.reportPaths=stepify_backend/coverage/lcov.info
sonar.dart.lcov.reportPaths=stepify_app/coverage/lcov.info

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
