sonar.projectKey=abdulraheem1308_Stepify_backend
sonar.organization=abdulraheem1308
sonar.projectName=Stepify Backend
sonar.projectVersion=1.0.0

# Path to source directories (required)
sonar.sources=src

# Exclude test files from code analysis
sonar.exclusions=**/*.spec.ts,**/*.e2e-spec.ts,test/**/*,performance/**/*

# Path to test directories
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

# Linter and Coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Quality Gates
sonar.qualitygate.wait=true
