# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends usage stats. Remove this line to disable.
install! 'cocoapods', :integrate_targets => true

# Flutter User Project
project 'Runner.xcodeproj'

# Load Flutter configuration and helpers
load File.join(File.dirname(__FILE__), 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
