name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'stepify_backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'stepify_backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./stepify_backend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of Sonar analysis

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './stepify_backend/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Lint Code
      run: npm run lint

    - name: Run Unit & E2E Tests with Coverage
      run: |
        npm run test:cov
        npm run test:e2e -- --passWithNoTests

    - name: Build Backend
      run: npm run build

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: stepify_backend
